package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tiansongyu/cs2_cheat/radar-relay/internal/config"
)

func TestTokenAndHashTokenCommands(t *testing.T) {
	var generated bytes.Buffer
	if err := run([]string{"token"}, strings.NewReader(""), &generated, &generated); err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimSpace(generated.String()), "\n")
	if len(lines) != 2 || !strings.HasPrefix(lines[0], "token: ") || !strings.HasPrefix(lines[1], "sha256: ") {
		t.Fatalf("unexpected token output: %q", generated.String())
	}
	var hashed bytes.Buffer
	token := strings.TrimPrefix(lines[0], "token: ")
	if err := run([]string{"hash-token"}, strings.NewReader(token+"\n"), &hashed, &hashed); err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(hashed.String()) != strings.TrimPrefix(lines[1], "sha256: ") {
		t.Fatal("generated and stdin hash commands disagree")
	}
}

func TestInitConfigStoresHashesOnly(t *testing.T) {
	path := filepath.Join(t.TempDir(), "relay.json")
	var output bytes.Buffer
	if err := run([]string{"init-config", "-out", path, "-origin", "https://radar.example.test", "-room", "room_one", "-static-dir", "/srv/web-radar"}, strings.NewReader(""), &output, &output); err != nil {
		t.Fatal(err)
	}
	payload, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(payload), " token") || strings.Contains(string(payload), "invite-token") {
		t.Fatal("generated config contains a plaintext token")
	}
	var cfg config.Config
	if err := json.Unmarshal(payload, &cfg); err != nil {
		t.Fatal(err)
	}
	if err := cfg.Validate(); err != nil {
		t.Fatal(err)
	}
	if len(cfg.Rooms) != 1 || cfg.Rooms[0].ID != "room_one" {
		t.Fatalf("unexpected generated rooms: %#v", cfg.Rooms)
	}
	if cfg.StaticDir != "/srv/web-radar" {
		t.Fatalf("generated staticDir is %q", cfg.StaticDir)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0600 {
		t.Fatalf("config permissions are %o, want 600", info.Mode().Perm())
	}
	if err := run([]string{"init-config", "-out", path, "-origin", "https://radar.example.test"}, strings.NewReader(""), &output, &output); err == nil {
		t.Fatal("init-config overwrote an existing config")
	}
}

func TestHealthcheckCommand(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
		writer.WriteHeader(http.StatusOK)
	}))
	defer server.Close()
	if err := healthcheck([]string{"-url", server.URL}); err != nil {
		t.Fatal(err)
	}
}

func TestCheckConfigAndExpectedOrigin(t *testing.T) {
	path := filepath.Join(t.TempDir(), "relay.json")
	var initOutput bytes.Buffer
	if err := run([]string{"init-config", "-out", path, "-origin", "https://radar.example.test", "-room", "room_one"}, strings.NewReader(""), &initOutput, &initOutput); err != nil {
		t.Fatal(err)
	}

	var output bytes.Buffer
	if err := run([]string{"check-config", "-config", path, "-origin", "https://radar.example.test"}, strings.NewReader(""), &output, &output); err != nil {
		t.Fatal(err)
	}
	if got := output.String(); !strings.Contains(got, "configuration valid") || strings.Contains(got, "sha256") || strings.Contains(got, "token:") {
		t.Fatalf("unsafe or unexpected check-config output: %q", got)
	}
	if err := run([]string{"check-config", "-config", path, "-origin", "https://other.example.test"}, strings.NewReader(""), &output, &output); err == nil || !strings.Contains(err.Error(), "publicOrigin mismatch") {
		t.Fatalf("origin mismatch was not detected: %v", err)
	}
}
