#pragma once

// Generated by scripts/generate_fixed_map_catalog.py from
// web-radar/public/maps/manifest.json.
// Do not edit this file directly; update the manifest and regenerate.

#include "core/game/fixed_map_radar.hpp"

#include <algorithm>
#include <array>
#include <string_view>

namespace game::fixed_map_catalog
{
    inline constexpr int kManifestVersion = 1;
    inline constexpr std::string_view kSourceProject =
        "pnxenopoulos/awpy-data";
    inline constexpr std::string_view kSourceRelease =
        "2000879";

    [[nodiscard]] inline const auto& all()
    {
        // Entries are sorted by canonical map id for binary lookup.
        static const std::array<fixed_map_radar::MapDefinition,
            16> definitions{{
            fixed_map_radar::MapDefinition{
                "ar_baggage",
                "Baggage",
                "maps/ar_baggage/radar.png",
                -1316.0F,
                1288.0F,
                2.539062F,
                1024.0F,
                1024.0F,
                {
                    fixed_map_radar::MapLevel{
                        "default",
                        "maps/ar_baggage/radar.png",
                        -5.0F,
                        10000.0F
                    },
                    fixed_map_radar::MapLevel{
                        "lower",
                        "maps/ar_baggage/radar_lower.png",
                        -10000.0F,
                        -5.0F
                    },
                }
            },
            fixed_map_radar::MapDefinition{
                "ar_shoots",
                "Shoots",
                "maps/ar_shoots/radar.png",
                -1368.0F,
                1952.0F,
                2.6875F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "ar_shoots_night",
                "Shoots Night",
                "maps/ar_shoots_night/radar.png",
                -1368.0F,
                1952.0F,
                2.6875F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "cs_italy",
                "Italy",
                "maps/cs_italy/radar.png",
                -2647.0F,
                2592.0F,
                4.6F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "cs_office",
                "Office",
                "maps/cs_office/radar.png",
                -1838.0F,
                1858.0F,
                4.1F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_ancient",
                "Ancient",
                "maps/de_ancient/radar.png",
                -2953.0F,
                2164.0F,
                5.0F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_ancient_night",
                "Ancient Night",
                "maps/de_ancient_night/radar.png",
                -2953.0F,
                2164.0F,
                5.0F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_anubis",
                "Anubis",
                "maps/de_anubis/radar.png",
                -2796.0F,
                3328.0F,
                5.22F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_cache",
                "Cache",
                "maps/de_cache/radar.png",
                -2000.0F,
                3250.0F,
                5.5F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_dust2",
                "Dust2",
                "maps/de_dust2/radar.png",
                -2476.0F,
                3239.0F,
                4.4F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_inferno",
                "Inferno",
                "maps/de_inferno/radar.png",
                -2087.0F,
                3870.0F,
                4.9F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_mirage",
                "Mirage",
                "maps/de_mirage/radar.png",
                -3230.0F,
                1713.0F,
                5.0F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_nuke",
                "Nuke",
                "maps/de_nuke/radar.png",
                -3453.0F,
                2887.0F,
                7.0F,
                1024.0F,
                1024.0F,
                {
                    fixed_map_radar::MapLevel{
                        "default",
                        "maps/de_nuke/radar.png",
                        -495.0F,
                        10000.0F
                    },
                    fixed_map_radar::MapLevel{
                        "lower",
                        "maps/de_nuke/radar_lower.png",
                        -10000.0F,
                        -495.0F
                    },
                }
            },
            fixed_map_radar::MapDefinition{
                "de_overpass",
                "Overpass",
                "maps/de_overpass/radar.png",
                -4831.0F,
                1781.0F,
                5.2F,
                1024.0F,
                1024.0F,
                {
                }
            },
            fixed_map_radar::MapDefinition{
                "de_train",
                "Train",
                "maps/de_train/radar.png",
                -2308.0F,
                2078.0F,
                4.082077F,
                1024.0F,
                1024.0F,
                {
                    fixed_map_radar::MapLevel{
                        "default",
                        "maps/de_train/radar.png",
                        -50.0F,
                        20000.0F
                    },
                    fixed_map_radar::MapLevel{
                        "lower",
                        "maps/de_train/radar_lower.png",
                        -5000.0F,
                        -50.0F
                    },
                }
            },
            fixed_map_radar::MapDefinition{
                "de_vertigo",
                "Vertigo",
                "maps/de_vertigo/radar.png",
                -3168.0F,
                1762.0F,
                4.0F,
                1024.0F,
                1024.0F,
                {
                    fixed_map_radar::MapLevel{
                        "default",
                        "maps/de_vertigo/radar.png",
                        11700.0F,
                        20000.0F
                    },
                    fixed_map_radar::MapLevel{
                        "lower",
                        "maps/de_vertigo/radar_lower.png",
                        -10000.0F,
                        11700.0F
                    },
                }
            },
        }};
        return definitions;
    }

    [[nodiscard]] inline const fixed_map_radar::MapDefinition* find(
        std::string_view mapId)
    {
        const auto& definitions = all();
        const auto match = std::lower_bound(
            definitions.begin(),
            definitions.end(),
            mapId,
            [](const fixed_map_radar::MapDefinition& definition,
                std::string_view id) noexcept
            {
                return std::string_view(definition.id) < id;
            });
        if (match == definitions.end()
            || std::string_view(match->id) != mapId)
        {
            return nullptr;
        }
        return &*match;
    }
}
