#!/bin/sh
set -eu

usage() {
    printf 'Usage: %s <radar-domain>\n' "$0" >&2
    printf 'Example: %s radar.example.com\n' "$0" >&2
    exit 2
}

if [ "$#" -ne 1 ]; then
    usage
fi

domain=$1
case "$domain" in
    ''|*[!abcdefghijklmnopqrstuvwxyz0123456789.-]*)
        printf 'Invalid domain: use a lowercase ASCII DNS hostname.\n' >&2
        exit 2
        ;;
esac
if ! printf '%s\n' "$domain" | awk -F. '
    length($0) > 253 || NF < 2 { exit 1 }
    {
        for (label_index = 1; label_index <= NF; label_index++) {
            if (length($label_index) > 63 ||
                $label_index !~ /^([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$/) {
                exit 1
            }
        }
        if ($NF !~ /[a-z]/) { exit 1 }
    }
'; then
    printf 'Invalid domain: use a lowercase ASCII DNS hostname.\n' >&2
    exit 2
fi

for command_name in curl docker; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
        printf '%s is required.\n' "$command_name" >&2
        exit 1
    fi
done
if ! docker compose version >/dev/null 2>&1; then
    printf 'Docker Compose v2 is required.\n' >&2
    exit 1
fi

script_dir=$(
    CDPATH=''
    cd "$(dirname "$0")"
    pwd
)
cd "$script_dir"

if [ ! -f .env ]; then
    printf 'Missing %s/.env.\n' "$script_dir" >&2
    exit 1
fi

docker compose config --quiet
configured_domain=$(docker compose config --environment | awk -F= '
    $1 == "RADAR_DOMAIN" {
        print substr($0, length($1) + 2)
        found++
    }
    END { if (found != 1) exit 1 }
')
if [ "$configured_domain" != "$domain" ]; then
    printf 'Requested domain %s does not match .env RADAR_DOMAIN=%s.\n' \
        "$domain" "$configured_domain" >&2
    exit 1
fi

for service_name in radar-relay caddy; do
    container_id=$(docker compose ps -q "$service_name")
    if [ -z "$container_id" ]; then
        printf '%s is not running.\n' "$service_name" >&2
        exit 1
    fi
    health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}missing{{end}}' "$container_id")
    if [ "$health" != healthy ]; then
        printf '%s health is %s, expected healthy.\n' "$service_name" "$health" >&2
        exit 1
    fi
done

docker compose exec -T radar-relay /radar-relay check-config \
    -config /run/secrets/relay-config.json \
    -origin "https://$domain" >/dev/null

# Production configs generated by this deployment enable aggregate metrics.
# Probe them only through the private listener; the public Caddy route must
# remain a 404.
if ! docker compose exec -T radar-relay /radar-relay healthcheck \
    -url http://127.0.0.1:8080/metrics; then
    printf 'Internal metrics are unavailable; set enableMetrics=true in the Relay config.\n' >&2
    exit 1
fi

relay_port=$(docker compose port radar-relay 8080 2>/dev/null || true)
if [ -n "$relay_port" ]; then
    printf 'Relay port 8080 is unexpectedly published as %s.\n' "$relay_port" >&2
    exit 1
fi

headers_file=
redirect_headers=
cleanup() {
    if [ -n "$headers_file" ]; then
        rm -f "$headers_file"
    fi
    if [ -n "$redirect_headers" ]; then
        rm -f "$redirect_headers"
    fi
}
trap cleanup EXIT
trap 'exit 130' HUP INT TERM

headers_file=$(mktemp "${TMPDIR:-/tmp}/radar-headers.XXXXXX")

https_url="https://$domain/"
status=$(curl --noproxy '*' --proto '=https' --tlsv1.2 --silent --show-error \
    --connect-timeout 5 --max-time 20 --output /dev/null \
    --dump-header "$headers_file" --write-out '%{http_code}' "$https_url")
if [ "$status" != 200 ]; then
    printf '%s returned HTTP %s, expected 200.\n' "$https_url" "$status" >&2
    exit 1
fi

for required_header in \
    'content-security-policy:' \
    'strict-transport-security:' \
    'x-content-type-options:' \
    'x-robots-tag:' \
    'referrer-policy:'; do
    if ! grep -qi "^$required_header" "$headers_file"; then
        printf 'Missing required response header: %s\n' "$required_header" >&2
        exit 1
    fi
done
if grep -qi '^server:' "$headers_file"; then
    printf 'The public response unexpectedly exposes a Server header.\n' >&2
    exit 1
fi

for internal_path in healthz readyz metrics; do
    status=$(curl --noproxy '*' --proto '=https' --tlsv1.2 --silent --show-error \
        --connect-timeout 5 --max-time 20 --output /dev/null \
        --write-out '%{http_code}' "https://$domain/$internal_path")
    if [ "$status" != 404 ]; then
        printf '/%s returned HTTP %s, expected 404.\n' "$internal_path" "$status" >&2
        exit 1
    fi
done

redirect_headers=$(mktemp "${TMPDIR:-/tmp}/radar-redirect.XXXXXX")
status=$(curl --noproxy '*' --proto '=http' --silent --show-error --connect-timeout 5 \
    --max-time 20 --output /dev/null --dump-header "$redirect_headers" \
    --write-out '%{http_code}' "http://$domain/")
case "$status" in
    301|308) ;;
    *)
        printf 'HTTP endpoint returned %s, expected a permanent HTTPS redirect.\n' "$status" >&2
        exit 1
        ;;
esac
if ! tr -d '\r' <"$redirect_headers" | grep -Fqix "location: https://$domain/"; then
    printf 'HTTP endpoint did not redirect to the expected HTTPS origin.\n' >&2
    exit 1
fi

plaintext_files=$(find secrets -maxdepth 1 -type f -name '*-credentials.txt' -print 2>/dev/null || true)
if [ -n "$plaintext_files" ]; then
    printf 'WARNING: plaintext credential files still exist:\n%s\n' "$plaintext_files" >&2
fi

printf 'Deployment verification passed for https://%s/\n' "$domain"
